//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FxTransfer
    {
        public long FxTransferId { get; set; }
        public int FxTVoucherNo { get; set; }
        public string FxTInvoiceNo { get; set; }
        public decimal FxTVoucherTypeId { get; set; }
        public string depositReceipt { get; set; }
        public decimal PartnerLedgerId { get; set; }
        public decimal CurrencyId { get; set; }
        public decimal amount { get; set; }
        public System.DateTime transactionDate { get; set; }
        public string Narration { get; set; }
        public Nullable<decimal> BankLedgerId { get; set; }
        public int version { get; set; }
        public string paymentMode { get; set; }
        public string chequeNo { get; set; }
        public Nullable<System.DateTime> chequeDate { get; set; }
        public string chequeComment { get; set; }
        public System.DateTime createdDate { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> lastUpdate { get; set; }
        public string lastUpdateBy { get; set; }
    }
}
